### ISSUE TITLE
Make Python bindings congruent

### ISSUE THREAD

**Issue by patrickhart** [bark-simulator/bark#112]
Avoid a mixed usage of def_property(..) and def(..).
Furthermore, the naming should also be made congruent.

**Comment by patrickhart** [comment]
We should agree on how we want to define properties, functions and classes.

**Comment by klemense1** [comment]
Rule:
- As long as the function has no arguments, it should be accessed by property.
- otherwise wrap the function

**Comment by juloberno** [comment]
What about setters and getters (setters do have an argument)? 
I suggest as rule: Properties in python should be directly linked to class members in c++

**Comment by patrickhart** [comment]
C++ functions have been renamed using CamelCase.
I propose we do the same for python.
Agree with the above-proposed ideas.

**Comment by patrickhart** [comment]
Adapted Python bindings are on branch `python_bindings`.
Have a look and check if these are complete.
