### ISSUE TITLE
intersection scenario: driving corridor und routing läuft falsch

### ISSUE THREAD

**Issue by juloberno** [bark-simulator/bark#141]
![GeneratedScenario](https://user-images.githubusercontent.com/49236264/66393955-1ff50280-e9d4-11e9-96a2-d0f78adaf1d6.png)

scenario generation uniform vehicle distribution creates the attached scenario with drawn driving corridors for the agents. The routing and corridor generation for one agent fails.

**Comment by juloberno** [comment]
example available on https://github.com/bark-simulator/bark/tree/intersection_scenario

**Comment by klemense1** [comment]
is this still valid? we now have better tooling for analyzing the map.

**Comment by patrickhart** [comment]
![roadgraph_laneid_24](https://user-images.githubusercontent.com/2854215/71967773-1746df00-3204-11ea-8b90-df079f4b4212.png)
![roadgraph_laneid_26](https://user-images.githubusercontent.com/2854215/71967784-1ada6600-3204-11ea-9a74-0764e85900fe.png)
