### ISSUE TITLE
Coding Guidelines are undefined

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#148]
- define them (Google Style Guide?)
- implement them
- use cpplint and pythonlint to enforce them? --> for that, it has to be integrated into the bazel build process, otherwise nobody will use it

**Comment by patrickhart** [comment]
Also additionally, I think that we should agree on a two-space indent everywhere (also in Python).

**Comment by klemense1** [comment]
implemented cpplint format file for autoformatting according to google style guide in  #160 
file can be created as follows: https://leimao.github.io/blog/Clang-Format-Quick-Tutorial/
