### ISSUE TITLE
The copy constructor of World does not set the member variable remove_agents_

### ISSUE THREAD

**Issue by AKreutz** [bark-simulator/bark#161]
The copy constructor of `World`
https://github.com/bark-simulator/bark/blob/c9a389c08d7e5b3dfbd4a9819d15491a306db285/modules/world/world.cpp#L23-L29
does not copy the value of the member variable `remove_agents_` from the old object to the new one. As a result, its value is undefined in the new object.

For me this results in problems when using the `Predict` function of `ObservedWorld`. The function will randomly return an `ObservedWorld` where the agent for which I want to obtain predictions has been removed.

**Comment by klemense1** [comment]
I fixed the copy constructor. Does it solve your problem?

**Comment by AKreutz** [comment]
That solves it, thank you.
