### ISSUE TITLE
can't parse Carla's maps in xodr_parser

### ISSUE THREAD

**Issue by tin1254** [bark-simulator/bark#164]
In xodr_parser.py , if the previous lane to the current one (except the two closet lanes to the reference line) is not a support lane type, then `get_lane_by_position` called in `create_cpp_lane_section` returns null/none

_Originally posted by @tin1254 in https://github.com/bark-simulator/carla-interface/issues/6#issuecomment-546036175_

**Comment by klemense1** [comment]
- pull request #173  solves it
- from a visual point, the map seems to be okay for Town01 and Town02
![Town01](https://user-images.githubusercontent.com/10078680/67956688-ceb3e980-fbf4-11e9-81c4-61aa3d915631.png)

![Town02](https://user-images.githubusercontent.com/10078680/67956698-d1aeda00-fbf4-11e9-8061-9ff7e17867cd.png)
