### ISSUE TITLE
Initial corridor generation

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#167]
We need a road-based routing for Lane-Changes. The Collision-Check should be for the road-based polygon and not for the driving corridor. This way, we would ommit the book-keeping of a current driving corridor.

However, we also still need concatenated Lanes (aka Driving Corridor) to have an easy API for "stupid" behavior models such as the IDM, which only follows one reference line.

**Comment by klemense1** [comment]
links to #194

**Comment by klemense1** [comment]
I think we should not book-keep any dynamically changing routing information DrivingCorridor. What is already implemented is that every agent tracks it's own CurrentLane.

I think what we also need is a new Lane class seperate from the OpenDrive Definition. Letting non-xodr-related stuff creep into that class is error-prone. And it also prevent's us from storing the lane-polygon directly in the lane class, which is why it's currently stored in the roadgraph. That means we currently always have to access the roadgraph for that.

Also, a new Lane-Class might allow us to store Right and Left Boundaries (and the repective road markings). The argument of driving direction is not suitable here, as we already have a definition of driving direction in the DrivingDirectionEvaluator.

**Comment by patrickhart** [comment]
#223
