### ISSUE TITLE
What else should a scenario contain? Desired speed, lane chage, etc. and how is it defined?

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#169]
Will be defined in the scenario/generation. Goal definition could be to adhere to the speed limit

Extend GoalDefinitionStateLimits

**Comment by patrickhart** [comment]
#225

**Comment by juloberno** [comment]
I think this can be closed: ConfigurableScenarioGeneration allows goal specification based on abstract keywords, left change, right change, but also more customized goals

Speed limits are parameterizable in GoalDefinitionStateLimitsFrenet
