### ISSUE TITLE
Route Intention: extraction of route hypotheses

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#174]
write a function that yields all possible routes from current pose (synergies with Andreas work?)

**Comment by klemense1** [comment]
map_interface already implements GetSplittingDrivingCorridors()
is that enough?

**Comment by juloberno** [comment]
what do you mean with intention. Should there be implemented a concept of intentions (class Intention) or is the focus only differentiating routes.

**Comment by patrickhart** [comment]
I think this should be implemented once a planners needs this.
