### ISSUE TITLE
Carla Map Town01 yields wrong map at junction

### ISSUE THREAD

**Issue by tin1254** [bark-simulator/bark#191]
In GenerateFromJunctions, we may also need to consider `laneLink` under `connection` in `junction` of opendrive map, but not connecting every lane independently to pre/successor

**Comment by tin1254** [comment]
![Screenshot from 2019-12-16 15-20-49](https://user-images.githubusercontent.com/22342030/70914796-fcc08200-2018-11ea-99db-2ebf687838c3.jpg)
![Screenshot from 2019-12-16 15-24-39](https://user-images.githubusercontent.com/22342030/70914745-e0244a00-2018-11ea-9701-04214635ba8c.jpg)
There are consecutive lane sections connected to each other. Right now in roadgraph, we omitted this information and connect each of them directly to pre/successor.

To fix this, we might also want to consider the contactPoint tag.
`<predecessor elementType="road" elementId="0" contactPoint="end"/>`

**Comment by klemense1** [comment]
in roadgraph.cpp, Line 449 `// TODO(@hart): there could be mult. lane_sections`
the issue with connecting multiple lane_sections  will probably be tackled at. what do you think? is that the problem we are facing with the junction?

**Comment by tin1254** [comment]
> in roadgraph.cpp, Line 449 `// TODO(@hart): there could be mult. lane_sections`
> the issue with connecting multiple lane_sections will probably be tackled at. what do you think? is that the problem we are facing with the junction?

Those lines of code are the reason of another issue I encountered at another junction, but not the one I show in https://github.com/bark-simulator/carla-interface/issues/4#issuecomment-560503364.

**Comment by tin1254** [comment]
> 
> 
> in roadgraph.cpp, Line 449 `// TODO(@hart): there could be mult. lane_sections`
> the issue with connecting multiple lane_sections will probably be tackled at. what do you think? is that the problem we are facing with the junction?

I think it would be great fix to bark, and it can surely alleviate the issues we faced on Carla maps

**Comment by klemense1** [comment]
[Town01_small_v1.zip](https://github.com/bark-simulator/bark/files/3983996/Town01_small_v1.zip)

**Comment by patrickhart** [comment]
#205
