### ISSUE TITLE
get_all_neighbours on city highway map does not return neighbours

### ISSUE THREAD

**Issue by cirrostratus1** [bark-simulator/bark#193]
When calling 
https://github.com/bark-simulator/bark/blob/f234609804b76e7038af8a9b4b965659473bbaef/modules/world/map/roadgraph.cpp#L273
on the [city highway straight map](https://github.com/bark-simulator/bark/blob/f234609804b76e7038af8a9b4b965659473bbaef/modules/runtime/tests/data/city_highway_straight.xodr) for either lane, no neighbours are returned.

**Comment by klemense1** [comment]
The roadgraph looks like this

![image](https://user-images.githubusercontent.com/10078680/71087928-9618a100-219d-11ea-89a2-855bf7e03cfa.png)

That means the unit test does not fully make sense. The notion of lanes within the roadgraph (and it's neighbour properties) does not directly translate to our "driving domain"

**Comment by klemense1** [comment]
@cirrostratus1 Is this issue still relevant?

**Comment by cirrostratus1** [comment]
I think with the explanation you gave, this is the intended behavior, since the other lanes are in the opposite direction, so they probably should in general not be considered for a driving corridor (maybe if overtaking is allowed?). However, for clarification maybe the uct_planner example should be changed, since it uses the map as a highway with two lanes of the same driving direction.

**Comment by patrickhart** [comment]
> I think with the explanation you gave, this is the intended behavior, since the other lanes are in the opposite direction, so they probably should in general not be considered for a driving corridor (maybe if overtaking is allowed?). However, for clarification maybe the uct_planner example should be changed, since it uses the map as a highway with two lanes of the same driving direction.

Is the driving direction clearly specified in the OpenDrive map? If not, I would close this issue.

**Comment by klemense1** [comment]
> 
> 
> > I think with the explanation you gave, this is the intended behavior, since the other lanes are in the opposite direction, so they probably should in general not be considered for a driving corridor (maybe if overtaking is allowed?). However, for clarification maybe the uct_planner example should be changed, since it uses the map as a highway with two lanes of the same driving direction.
> 
> Is the driving direction clearly specified in the OpenDrive map? If not, I would close this issue.

We have agreed to a definition based on the sign of the lane position, which is used in https://github.com/bark-simulator/bark/blob/8294df8676f93db4137af742551d1d9f3adbac8e/modules/world/map/local_map.cpp#L37

**Comment by patrickhart** [comment]
#223
