### ISSUE TITLE
Clean up Driving Corridor Generation

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#194]
In LocalMap::Generate (https://github.com/bark-simulator/bark/blob/master/modules/world/map/local_map.cpp#57) and in 
LocalMap::RecalculateDrivingCorridor(https://github.com/bark-simulator/bark/blob/master/modules/world/map/local_map.cpp#74)
we write 
`std::vector<LanePtr> lanes;`
`map_interface_->FindNearestLanes(point, 1, lanes);`
`LanePtr current_lane = lanes.at(0);`

However, we could use MapInterface::FindLane() instead

**Comment by klemense1** [comment]
DrivingCorridors should be calculated only once when generating the map. This would ommit the need to recalulate it.

**Comment by patrickhart** [comment]
#223
