### ISSUE TITLE
Use shared_ptr for ParameterServer

### ISSUE THREAD

**Issue by patrickhart** [bark-simulator/bark#211]
Would improve usability.

**Comment by patrickhart** [comment]
When you try to acces the ParameterServer in any of the World.cpp functions a crash occurs.

**Comment by juloberno** [comment]
How do you know that the crash arises due to using the raw pointer?

**Comment by patrickhart** [comment]
Not sure, but try accessing a variable using the ParameterServer in, for example, DoPlanning()

**Comment by patrickhart** [comment]
Would lead to circular dependencies.
