### ISSUE TITLE
RoadCorridor instead of DrivingCorridors

### ISSUE THREAD

**Issue by patrickhart** [bark-simulator/bark#218]
The RoadCorridor is an agent specific class that contains roads and lanes on which the agent is driving.

Additionally, there is a LaneCorridor that contains merged lanes that are valid until the final s-value (length of the center-line).

The RoadCorridor is generated using the RoadGraph and Xodr-Map.

**Comment by klemense1** [comment]
- Add DrivingDirection to XodrLane
- RoadID & Driving Direction for Road Corridor Hash

**Comment by patrickhart** [comment]
#223
