### ISSUE TITLE
RoadGraph Extension

### ISSUE THREAD

**Issue by patrickhart** [bark-simulator/bark#219]
The RoadGraph needs to have additional functionalities and data.

Requested functionalities:
- `XodrRoadId GetNextRoad(road_id)`
-  Change Parser to include road connections
- `XodrLaneId GetLeftLane(lane_id)`
- `XodrLaneId GetRightLane(lane_id)`
- `XodrLaneId GetLeftBoundary(lane_id)`
- `XodrLaneId GetRightBoundary(lane_id)`
- `XodrLaneId GetNextLane(lane_id)`
- `Line GetCenterLine(lane_id)`
- `std::vector<XodrRoadId> GetRoadIdsForPath(road_start_id, road_end_id)`

**Comment by patrickhart** [comment]
Mocked functions on branch road_corridor

**Comment by klemense1** [comment]
Updated interfaces

```
  XodrLaneId GetNextLane(const XodrLaneId& lane_id)

  std::vector<XodrRoadId> FindRoadPath( const XodrRoadId& startid, const XodrRoadId& goalid)
```

We depricate   `XodrRoadId GetNextRoad(const XodrRoadId& road_id) {}`

**Comment by patrickhart** [comment]
#223
