### ISSUE TITLE
Refactor GetAgentInFront()

### ISSUE THREAD

**Issue by patrickhart** [bark-simulator/bark#224]
Do not recalculate the Frenet coordinates in each step (as the s-value is in the RoadCorridor).

Furthermore, is the ObservedWorld the right class to contain this function?

**Comment by juloberno** [comment]
Where do we have the s-value in road corridor?

**Comment by patrickhart** [comment]
> Where do we have the s-value in road corridor?

We do have a s-value in the LaneCorridors: https://github.com/bark-simulator/bark/blob/58133c11c49fdc172efa287710c83a87f2e44db3/modules/world/map/lane_corridor.hpp#L60

**Comment by juloberno** [comment]
It seems the benefit of this method is only saving the lateral coordinate calculation in each step.
