### ISSUE TITLE
Agent Polygon does not consider Wheelbase when transforming from State

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#228]
- polygon obtained from kinematic state does not use the wheelbase
- that means that the collision shape does not over approximate the true vehicle shape

center position of polygon should be calculated using
xcenter = x+L/2*cos(theta)
ycenter = y+L/2*cos(theta)

**Comment by patrickhart** [comment]
If the center of the polygon is aligned with the wheelbase a rotation should yield the same?
