### ISSUE TITLE
Bazel test failed with TIMEOUT for python examples on macOS

### ISSUE THREAD

**Issue by Jiraphapa** [bark-simulator/bark#23]
Some test cases from running `bazel test //...` are failed with `TIMEOUT` on macOS, it seems to be a problem with Python (virtual environment was activated). I've also tried to use `--test_timeout` on each failed test case but it seems to take forever. Below are the details and the attachments: saved output from terminal and testlogs.

**OS**: macOS Mojave 10.14.5
**Bazel version**: Build label: 0.15.0
**Python version**: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:39:00) 
**GCC**: 4.2.1 (Apple Inc. build 5666) (dot 3) on darwin
**Virtualenv version**: 16.5.0

[Bark Terminal Saved Output.txt](https://github.com/bark-simulator/bark/files/3293535/Bark.Terminal.Saved.Output.txt)

[Output from 'bazel test ::examples-od8_const_vel_one_agent'.txt](https://github.com/bark-simulator/bark/files/3294083/Output.from.bazel.test.examples-od8_const_vel_one_agent.txt)

[bazel-testlogs.zip](https://github.com/bark-simulator/bark/files/3293549/bazel-testlogs.zip)

[Output from 'bazel run ::examples-od8_const_vel_one_agent'.txt](https://github.com/bark-simulator/bark/files/3294054/Output.from.bazel.run.examples-od8_const_vel_one_agent.txt)

[Python Output.txt](https://github.com/bark-simulator/bark/files/3293556/Python.Output.txt)

**Comment by Jiraphapa** [comment]
So it's a problem with 'pybind11' type binding library on Python 3.7 on macOS. By changing configuration of "pybind11" from 2.2.3 to version 2.3.0 in WORKSPACE file did solve the issue.

**Comment by klemense1** [comment]
updated WORKSPACE file for pybind version 2.3.0

**Comment by klemense1** [comment]
moved to master
