### ISSUE TITLE
Incorrect Interaction Term in IDM

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#236]
spatial distance between two vehicles is not calculated correctly, see https://github.com/bark-simulator/bark/blob/master/modules/models/behavior/idm/idm_classic.cpp#L47 

it only works correctly if vehicle controlled by idm is at s=0

**Comment by patrickhart** [comment]
Branch `fix_idm_model` should resolve this problem.

**Comment by klemense1** [comment]
solved by #240
