### ISSUE TITLE
GoalDefinitionTimeConsecutive

### ISSUE THREAD

**Issue by juloberno** [bark-simulator/bark#273]
We need a GoalDefinition modeling consecutive occurence of time independents goals such as GoalDefinitionStateLimitsFrenet or GoalDefinitionPolygon. Maybe a simple wrapper class with parameter required consecutive time steps.

**Comment by patrickhart** [comment]
As this is a planner specific feature request, I will close this issue for now.
Should be added with the planner's implementation.
