### ISSUE TITLE
Installation Instructions bazel config

### ISSUE THREAD

**Issue by tom-doerr** [bark-simulator/bark#284]
What is meant by
"1. Clone the repository, change to base repository directory; change the .bazelrc: build --action_env CC=/usr/bin/gcc-7 --cxxopt='-std=c++14' "  ?

Does it mean I need to change 
```
build --cxxopt='-std=c++14'
```
to
```
build --action_env CC=/usr/bin/gcc-7 --cxxopt='-std=c++14'
``` 
?

**Comment by patrickhart** [comment]
Either you do this or you set gcc7 as your default compiler.

**Comment by tom-doerr** [comment]
Thanks for the quick response!
I opened a pull request to clarify this in the readme: https://github.com/bark-simulator/bark/pull/285

**Comment by patrickhart** [comment]
#299
