### ISSUE TITLE
bad_weak_ptr with DefaultParams.AddChild

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#292]
DefaultParams throw a bad_weak_ptr, when calling AddChild

see https://github.com/bark-simulator/bark/blob/default_params_add_child/modules/commons/tests/params_test.cc#L61-L69

Either we fix, or we depricate DefaultParams

**Comment by juloberno** [comment]
Related to #296

**Comment by patrickhart** [comment]
#370
