### ISSUE TITLE
Fix WorldAtExecutionStep 

### ISSUE THREAD

**Issue by juloberno** [bark-simulator/bark#297]
WorldAtExecutionStep can calculate world states at intermediate  time steps, e.g. meaningful for smooth rendering of videos.

Currently, the execution model interpolation seems to be broken for intermediate execution steps.

Goal: Fix WorldAtExecutionStep, test with VideoRenderer, render_intermediate_steps=...

**Comment by patrickhart** [comment]
@juloberno my suggestion would be to refactor the agent's Execute function and let this handle the execution model itself.
It would be way more neat, if the Execution model would return a state instead of a trajectory. However, what about the actions? Should these also be interpolated?

**Comment by patrickhart** [comment]
Resolved in development branch with PR #364
