### ISSUE TITLE
Add geoReference into xodr files and center the map to origin

### ISSUE THREAD

**Issue by tin1254** [bark-simulator/bark#360]
Map issue encountered during integrating RSS:
1. [One of the dependences](https://github.com/carla-simulator/map) of RSS requires geoReference in the header to project points
2. In city highway straight, the road has the coordinates above 5000, which is invalid for the dependence of RSS. Centering the road to the origin solves the issue.

**Comment by patrickhart** [comment]
Can this not be internally be done for the calculations of the RSS?
It is important for the map to remain at its position for applications such as dataset replays.

**Comment by klemense1** [comment]
I don't think this will break dataset replay. @tin1254 can you please check if the german and chinese merging maps work?

**Comment by patrickhart** [comment]
If it is only saved as semantic information then no. However, if the map is re-centered the coordinates will not match.

**Comment by klemense1** [comment]
german and chinese merging maps have this already. the maps we made manually (city highway straight) are missing this information...

**Comment by patrickhart** [comment]
alright, then no problem!

**Comment by tin1254** [comment]
> I don't think this will break dataset replay. @tin1254 can you please check if the german and chinese merging maps work?

I found a bug running on those maps, I will try this after fixing the bug

**Comment by tin1254** [comment]
> I don't think this will break dataset replay. @tin1254 can you please check if the german and chinese merging maps work?

chinese works but german doesn't, it's because of the coordinate values of the map are too large
