### ISSUE TITLE
The xodr_parser raises a ValueError during lane mark parsing for Road Mark Type `none`

### ISSUE THREAD

**Issue by AKreutz** [bark-simulator/bark#46]
Lanes can have the Road Mark Type `none`, as in `4way_intersection.xodr:27`. These `roadMark`-tags do not have a `width` property, and therefore this code section fails (in particular line 335):

https://github.com/bark-simulator/bark/blob/5862c2d7564f8624db84933c80cd7e3299755ac1/modules/runtime/commons/xodr_parser.py#L331-L336

A solution would be to exclude road marks of type `RoadMarkType.none` from parsing, or parse them differently.

@klemense1

**Comment by klemense1** [comment]
fixed by only parsing roadmark types solid or broken
see #41
