### ISSUE TITLE
Roadmap of this project

### ISSUE THREAD

**Issue by valaxkong** [bark-simulator/bark#475]
Could you team show up your future roadmap about this project?

**Comment by patrickhart** [comment]
We would want to improve the usability of BARK, integrate more elaborate behavior models and planners, and extend BARK towards a verification and validation (V&V) tool.

What is your interest using BARK for? Let us know and we can talk about it.

**Comment by valaxkong** [comment]
@patrickhart I'm interested in using BARK as a V&V tool. Actually, I have developed a very similar V&V tool for internal use. I believe that a generally accepted V&V benchmark are of great significance to both industry and academia. BARK is promising to be a generally accepted benchmark. Thanks for your work!

**Comment by patrickhart** [comment]
@valaxkong if you have any concrete idea what is missing or what should be added to the roadmap feel free to let us know. Of course, all kind of contributions to BARK are welcome.

**Comment by valaxkong** [comment]
@patrickhart 
I have seen the carla-interface project. It use carla client to interaction with Carla. I think BARK should have a similar mechanism to  make testing easy. At present, I'm trying to build BARK client api to enable cosimulation with my system. Do you have some suggestions?

**Comment by patrickhart** [comment]
The carla-interface repo can be seen as a starting point for building interfaces certainly. 

- I would suggest to implement and/or overload the BARK runtime by introducing an async function `ReceiveData(..)` that waits for data (such as e.g. object lists that are then added to the BARK world in each step).
- Once the BARK world has been filled with external data, one can use the behavior models in BARK and the world.Step(..) function to advance the world-state
- Additionally a function could broadcast the data, such as `StreamBARKData(..)` with which an external simulator could be updated -- depending on the operational mode.

**Comment by valaxkong** [comment]
OK! I'll try to do it like you said.
One other thing, would you like to offer a web display feature to show what is happening in BARK?

**Comment by patrickhart** [comment]
> OK! I'll try to do it like you said.
> One other thing, would you like to offer a web display feature to show what is happening in BARK?

In my opinion that certainly would be nice. We were thinking of using [streetscape/xiviz](https://avs.auto/) and if we have the resources to do so we might tackle that next year.

**Comment by valaxkong** [comment]
I sincerely wish you have enough resource to keep maintaining and promoting this repo.

Would you like to add some comfort related evaluations?

**Comment by patrickhart** [comment]
Sure, that would be a great addition for the evaluation and can be done rather quickly depending on the comfort metric.
If e.g. the comfort of driving is defined as having minimum jerk, this would also lead to safer driving maneuvers as the physical limits of the vehicle would be avoided.

And: We always welcome contributions to BARK. Generic interfaces would certainly be a great addition!

**Comment by valaxkong** [comment]
I will create a pull request when I complete a initial version of general interfaces.

Minimun jerk is good enough to be the first metric to evaluation comfort of driving. Do you notice this research [SMARTS](https://github.com/huawei-noah/SMARTS)? It propounds a lot of valuable metrics.

**Comment by patrickhart** [comment]
Yes, we are aware of the related projects in the field, but did not have find to have a closer look at it.
We mainly focused on analysing Carla, Sumo, and others.

**Comment by valaxkong** [comment]
Im not very familiar with SUMO. And I wonder if SUMO can reproduce a scenario with some way. If the answer is yes, it will be greate to use SUMO to drive environment dynamic.
