### ISSUE TITLE
I have a mess in mind, is anyone here who could instruct me how to successfully install the framework "bark-ml" step by step?

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark#488]

**Comment by klemense1** [comment]
Hi, could you specify the problem you are facing? Did you follow the instructions? https://github.com/bark-simulator/bark/blob/master/docs/source/installation.md

**Comment by tinmodeHuang** [comment]
yeah, I managed to install "bark'' successfully with that instruction, but failed to see the GUI of bark-ML while installing "bark-ML"

**Comment by patrickhart** [comment]
Refer to: https://github.com/bark-simulator/bark-ml/issues/84
