### ISSUE TITLE
Only support for one lanesection per road for OpenDrive

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#49]
in `void Roadgraph::GeneratePreAndSuccessors(OpenDriveMapPtr map)`, predesssor and successor lane section are currently always assumed to be in the predecessing and successing road element. Thus, we currently only support one lanesection per road element. But OpenDrive also allows to define more than one lane section per road element.

**Comment by patrickhart** [comment]
Might be related to #191

**Comment by patrickhart** [comment]
#205
