### ISSUE TITLE
cannot open the source file

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark#498]
In face of the errors, is there any advices to give me? thanks ahead of time.
I tried to modify the includePath-es, but it didn't seem to work.

![2021-03-22 22-05-49 的屏幕截图](https://user-images.githubusercontent.com/65896325/112002543-f6458200-8b5a-11eb-9634-2d10f99acbe2.png)

**Comment by patrickhart** [comment]
These errors are "just" VS-Code specific that cannot find the includes.

**Comment by tinmodeHuang** [comment]
so VS code of specific version is to blame for these errors

**Comment by patrickhart** [comment]
Not a specific version, but VS-Code is unable to locate the, e.g., boost source files. You can try to install Bazel extensions for VS-Code, but I am not sure if this will fix these issues.

**Comment by tinmodeHuang** [comment]
there is still the errors after installing the Bazel 0.4 extension, did you developers also meet the same trouble that VS Code cannot locate these source files besides boost ?

![2021-03-23 18-46-16 的屏幕截图](https://user-images.githubusercontent.com/65896325/112134852-1e3eef00-8c08-11eb-9bec-90c24c8ecc26.png)

**Comment by patrickhart** [comment]
These problems are generated by cpplint as far as I know. Maybe you can try to find a fix somehow this way.

**Comment by tinmodeHuang** [comment]
there are still the problems after installing successfully bark on another machine. the bark directory is opened by selecting file→open directory once VS Code is installed and configured with the extensions including bazel, cpplint, python and C++. I'm thinking about what's wrong in the process

**Comment by patrickhart** [comment]
Under macOS (latest Catalina) and using VS-Code 1.54, I do not get these error messages shown. Do you have similar problems?  @klemense1 @juloberno

**Comment by tinmodeHuang** [comment]
could you pay a little attention to #499? please

**Comment by patrickhart** [comment]
I close this issue then as resolved as it seems a VS-Code/Linux specific error. If you find a fix for it, feel free to share it with us!

**Comment by tinmodeHuang** [comment]
in fact, the problem isn't resolved.
