### ISSUE TITLE
output is re-assigned as the variable embeddings

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark#505]
I wonder what the 2nd statement in the snippet does, which have confused me for long.
```C++
    output, network_state = self._encoder(embeddings, training=training)  # its call func be called
    output = embeddings
```

**Comment by patrickhart** [comment]
As this is BARK-ML specific please consider posting it there. Also, feel free to create a PR for changing it.
Best,
Patrick

**Comment by tinmodeHuang** [comment]
sorry for no additon to detail it, read the complement, please!

**Comment by patrickhart** [comment]
BARK-ML can be found here: https://github.com/bark-simulator/bark-ml/tree/master/utils

related issues should be posted there

**Comment by tinmodeHuang** [comment]
I don't understand it, you mean the question ought to be posted in the project bark-ml.
