### ISSUE TITLE
A lane and its successor lane are sometimes not connected

### ISSUE THREAD

**Issue by AKreutz** [bark-simulator/bark#51]
When working with the file `4way_intersection.xodr` I noticed that in some cases there are gaps between a lane and the next succeeding lane. This can be seen here:
![successor_lanes](https://user-images.githubusercontent.com/18612662/61721406-b36d4e80-ad68-11e9-9034-c3aba7cadefa.png)
According to the roadgraph, lines of the same color are in a predecessor/successor relationship. For the (global) LaneIds 35->3, 37->10, 46->29 and 47->50 there is a gap between the corresponding lines.
A test case for this error is implemented in #52
@klemense1

**Comment by klemense1** [comment]
commented in https://github.com/bark-simulator/bark/issues/73
closing
