### ISSUE TITLE
Cannot debug c++ and python

### ISSUE THREAD

**Issue by Rx-SUN** [bark-simulator/bark#543]
Hello, I followed the instructions in https://bark-simulator.readthedocs.io/en/latest/debugging.html and I still failed jumping from python file to c++ file.

I successfully ran  `bazel build //... --compilation_mode=dbg` and `readelf --debug-dump=decodedline core.so`(I did not find bark.so so I copied core.so to bark folder). I then followed the 1.2.3.4 steps but I cannot jump to c++ file and debug.

Here is my launch.json file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {
                "PYTHONPATH": "${workspaceFolder}/bazel-bark/tools/debug"
  }
        },
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bazel-bin/bark/models/tests/behavior_motion_primitive_test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        },
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/home/rx-sun/anaconda3/envs/bark_env/bin/python",
            "cwd" : "${workspaceFolder}",
            "processId": "${command:pickProcess}",
            "MIMode": "gdb",
            "sourceFileMap" : {"/proc/self/cwd/": "${workspaceFolder}"}
            }
    ]
}
```
![Screenshot from 2021-09-10 12-53-33](https://user-images.githubusercontent.com/50556191/132843388-57801113-0388-40d8-a362-c550e6dc52e6.png)
![Screenshot from 2021-09-10 12-53-38](https://user-images.githubusercontent.com/50556191/132843393-272c7010-c123-4c64-b111-a4c9c5c1ce3b.png)
![Screenshot from 2021-09-10 12-57-31](https://user-images.githubusercontent.com/50556191/132843457-822c0ac1-3b3e-4844-bf72-487c51bdcc90.png)

**Comment by patrickhart** [comment]
The `bark.so` file is located in the `bazel-bin`folder. The main thing to make debugging work is to add this path in the `launch.json` and to build the project in debug mode. The other thing is that you then can execute the file in question whilst being in that file and pressing `F5`.

**Comment by klemense1** [comment]
Did this resolve the issue? Can we close it?

**Comment by Rx-SUN** [comment]
> 

Yes, thank you very much !

**Comment by klemense1** [comment]
Great! If you like our work, please star BARK to make it more visible to others.
I will close this issue then...
