### ISSUE TITLE
Add Versions of Python dependencies to Requirements.txt 

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#67]

**Comment by klemense1** [comment]
'bash install.sh' yields:
ERROR: tfp-nightly 0.9.0.dev20190902 has requirement cloudpickle==1.1.1, but you'll have cloudpickle 1.2.1 which is incompatible.

**Comment by patrickhart** [comment]
Running `pip freeze` locally yields versions that cannot be found in the docker image.

**Comment by patrickhart** [comment]
#205
