### ISSUE TITLE
Bazel Error with Submodule MCTS Planner

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#75]
see https://circleci.com/gh/bark-simulator/bark/240

`ERROR: /home/esterle/.cache/bazel/_bazel_esterle/686875265778f8801c25fece24de0587/external/planner_uct/src/BUILD:1:1: no such package '@bark_project//modules': BUILD file not found in directory 'modules' of external repository @bark_project and referenced by '@planner_uct//src:planner_uct_single_agent'
ERROR: Analysis of target '//modules/models/behavior/plan:uct_single_agent' failed; build aborted: no such package '@bark_project//modules': BUILD file not found in directory 'modules' of external repository @bark_project
INFO: Elapsed time: 0.296s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @com_github_eigen_eigen; fetching
    Fetching @gtest; fetching
    Fetching @boost; fetching
`

**Comment by klemense1** [comment]
- pushed current (broken) master to branch planner_submodule_bug
- fixed master for now by commenting out @planner_uct//src:planner_uct_single_agent in behavior/plan BUILD file

**Comment by juloberno** [comment]
Now external planners are built only if - - define planner_uct=true is added to the bazel call. Problems with planner repositories thus do not influence the main bark build
