### ISSUE TITLE
nicer visualization of vehicles in matplotlib viewer

### ISSUE THREAD

**Issue by juloberno** [bark-simulator/bark#77]
integrate drawing of svg vehicle shape into matplotlib viewer:
- replace each agents polygon with appropriately scaled vehicle svg
- maybe have the collision shape additionally drawn with certain transparency below

**Comment by klemense1** [comment]
what do you mean with svg? do we have one? or do you mean the CarLimousine shape from modules/geometry/standard_shapes.hpp?
