### ISSUE TITLE
Function `modules::world::objects::Agent::set_goal_definition` does not update the goal definition of the Agent's local_map

### ISSUE THREAD

**Issue by AKreutz** [bark-simulator/bark#79]
The function `modules::world::objects::Agent::set_goal_definition` should make it possible to change the GoalDefinition of an Agent after its creation. In its implementation
https://github.com/bark-simulator/bark/blob/7c3a5ac0d20bcd84ac17d4d82b9e69c2fa3ad6d0/modules/world/objects/agent.hpp#L88-L93
the function only changes the GoalDefinition of the Agent, but not the GoalDefinition of the Agent's LocalMap.
The subsequent call to
https://github.com/bark-simulator/bark/blob/7c3a5ac0d20bcd84ac17d4d82b9e69c2fa3ad6d0/modules/world/objects/agent.cpp#L118-L126
therefore causes
https://github.com/bark-simulator/bark/blob/7c3a5ac0d20bcd84ac17d4d82b9e69c2fa3ad6d0/modules/world/map/local_map.cpp#L46-L51
to generate the new LocalMap using the old GoalDefinition.
The straightforward solution would be to add a function `modules::world::map::LocalMap::set_goal_definition` and to call it in `modules::world::objects::Agent::set_goal_definition`, which I tried in my fork of the repo. This approach works for what I want to do, however it causes the test //examples:scenario_generation_dump to fail. This makes me wonder if I understood the intended use of set_goal_definition correctly.
@klemense1

**Comment by patrickhart** [comment]
Should be resolved.
