### ISSUE TITLE
Use proper Logger instead of print

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#83]

**Comment by patrickhart** [comment]
In order to make the logging easier and to not clutter the console, we should use logging instead of print and agree upon a common schemata (log-levels etc.).

**Comment by juloberno** [comment]
replaced std::couts with glog commands, except in test code

for simplictiy, we use the provided log levels and macros of glog. (LOG_EVERY_N, VLOG, DLOG...)
