### ISSUE TITLE
Write OpenDrive Parser in C++

### ISSUE THREAD

**Issue by klemense1** [bark-simulator/bark#84]
The reason is that it complicates our test and debugging tool chain that we always need python to parse the map.

**Comment by patrickhart** [comment]
As an alternative we could pickle maps and provide them in a serialized way.

**Comment by klemense1** [comment]
that is pretty much what Apollo & Carla are doing.

**Comment by klemense1** [comment]
we now have reasonable xodr_maps in cpp through MakeXodrMap...(), so I am closing this issue
